import { useState } from 'react'
import { ChartResponse } from '@/lib/types'
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'

interface Props {
  chart: ChartResponse
}

export function ChartImageCard({ chart }: Props) {
  const [loaded, setLoaded] = useState(false)
  const [error, setError] = useState(false)
  
  const typeLabels: Record<string, string> = {
    distribution:    'Distribution',
    categorical_bar: 'Categorical',
    heatmap:         'Correlation',
    scatter:         'Scatter',
    line_trend:      'Trend',
    anomaly_scatter: 'Anomaly',
    cluster_scatter: 'Clustering',
    grouped_bar:     'Comparison',
    box_plots:       'Box Plot',
  }
  
  return (
    <Card className="overflow-hidden bg-card border-border">
      <CardHeader className="pb-2">
        <div className="flex items-start justify-between gap-2">
          <CardTitle className="text-sm font-semibold leading-snug break-words">
            {chart.title}
          </CardTitle>
          <Badge variant="secondary" className="shrink-0 text-xs">
            {typeLabels[chart.type] ?? chart.type}
          </Badge>
        </div>
        <CardDescription className="text-xs line-clamp-2">
          {chart.description}
        </CardDescription>
      </CardHeader>
      
      <CardContent className="p-0">
        {/* Shimmer skeleton shown while image loads */}
        {!loaded && !error && (
          <div className="relative h-[280px] w-full overflow-hidden bg-muted">
            <div className="absolute inset-0 -translate-x-full animate-[shimmer_1.5s_infinite]
                            bg-gradient-to-r from-transparent via-white/5 to-transparent" />
          </div>
        )}
        
        {/* The actual chart image */}
        <img
          src={chart.image_url}
          alt={chart.title}
          className={cn(
            "w-full h-auto max-h-[350px] object-contain transition-opacity duration-300",
            loaded ? "opacity-100" : "opacity-0 h-0"
          )}
          onLoad={() => setLoaded(true)}
          onError={() => setError(true)}
          loading="lazy"      // browser-native lazy loading
        />
        
        {/* Error state */}
        {error && (
          <div className="flex h-[280px] items-center justify-center flex-col gap-2
                          text-muted-foreground text-sm">
            <span className="text-2xl">📊</span>
            <span>Chart unavailable</span>
          </div>
        )}
      </CardContent>
      
      <CardFooter className="py-2 px-4">
        <p className="text-xs text-muted-foreground">
          {chart.type === 'heatmap'
            ? 'Blue = positive correlation · Red = negative'
            : chart.type === 'anomaly_scatter'
            ? 'Red × = anomalies · Blue dots = normal'
            : chart.type === 'cluster_scatter'
            ? 'Colors represent distinct data clusters'
            : 'Generated by DataSage analysis pipeline'
          }
        </p>
      </CardFooter>
    </Card>
  )
}
